import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errores = [];
p.on('pageerror', e => errores.push(String(e)));
p.on('console', m => { if (m.type() === 'error') errores.push(m.text()); });
await p.goto('http://localhost:4173/Simulador-VM/');
await p.getByLabel(/nombre o alias/i).fill('Demo');
await p.getByRole('button', { name: 'Crear' }).click();
await p.getByRole('button', { name: /^Empezar$/ }).first().click();
await p.waitForTimeout(3000);
await p.getByRole('button', { name: 'Pausa insp.' }).click();
await p.waitForTimeout(4000);
await p.getByRole('button', { name: 'Pausa esp.' }).click();
await p.waitForTimeout(6000);
await p.screenshot({ path: process.argv[2] ?? 'shot.png' });
console.log('errores:', errores);
await b.close();
